apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/marwan-ghonem/mongodb-azure.git
    targetRevision: main
    path: base
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-prod-aks-psmdb-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
