architecture: replicaset
replicaCount: 3

auth:
  enabled: true
  rootUser: root
  rootPassword: $up3rP@ssw0rd 
  username: admin
  password: $up3rP@ssw0rd
  database: mydatabase

resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 2
    memory: 4Gi

persistence:
  enabled: true
  size: 8Gi

arbiter:
  enabled: false
metrics:
  enabled: false

passwordUpdateJob:
  enabled: false

livenessProbe:
  enabled: true
readinessProbe:
  enabled: true

service:
  type: ClusterIP
  port: 27017

image:
  registry: docker.io
  repository: bitnami/mongodb
  tag: 7.0.4-debian-11-r0

tls:
  enabled: false

volumePermissions:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/bitnami-shell
    tag: latest

externalAccess:
  enabled: false

