replsets:
  - name: rs0
    size: 3
    volumeSpec:
      pvc:
        storageClassName: default
        resources:
          requests:
            storage: 10Gi
podSpec:
  affinity:
    antiAffinityTopologyKey: "kubernetes.io/hostname"
  containers:
    - name: mongod
      resources:
        requests:
          cpu: "2"
          memory: "4Gi"
        limits:
          cpu: "2"
          memory: "4Gi"

